package calculadoramatrices;

import auxiliar.Auxiliar;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Manuel Muñoz
 */
public class Principal extends javax.swing.JFrame {

    private Double resultado = 0.0;
    private int numAcabados;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jComboBox1.addItem("Determinante");
        jComboBox1.addItem("Multiplicación");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Operación a realizar:");
        jPanel2.add(jLabel1);

        jPanel2.add(jComboBox1);

        jLabel3.setText("Número de ordenadores:");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextField1);

        jLabel2.setText("Tamaño Matriz A (XxY)");
        jPanel2.add(jLabel2);
        jPanel2.add(jTextField2);

        jLabel5.setText("Tamaño Matriz B (XxY)");
        jPanel2.add(jLabel5);
        jPanel2.add(jTextField3);

        getContentPane().add(jPanel2);

        jButton2.setText("Comenzar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        getContentPane().add(jPanel4);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jPanel3.add(jLabel6);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String operacion = (String) jComboBox1.getSelectedItem();
        String[] partes = jTextField2.getText().split("x");
        int numPCs = Integer.valueOf(jTextField1.getText());
        int filasA = Integer.valueOf(partes[0]);
        int colA = Integer.valueOf(partes[1]);

        switch (operacion) {
            case "Determinante":
                if (filasA == colA) {

                    if (numPCs == filasA || numPCs == 1) {

                        new PantallaIntermedia(Integer.valueOf(jTextField1.getText()), (String) jComboBox1.getSelectedItem(), jTextField2.getText(), jTextField3.getText()).setVisible(true);
                        this.setVisible(false);
                    } else {

                        jLabel6.setText("Nº PCs debe coincidir con el tam de la matriz!");

                    }

                } else {
                    jLabel6.setText("La matriz no es cuadrada!");

                }

                break;
            case "Multiplicación":
                partes = jTextField3.getText().split("x");
                int filasB = Integer.valueOf(partes[0]);
                if (colA == filasB) {

                    if (filasA % numPCs == 0 || numPCs == 1) {

                        new PantallaIntermedia(Integer.valueOf(jTextField1.getText()), (String) jComboBox1.getSelectedItem(), jTextField2.getText(), jTextField3.getText()).setVisible(true);
                        this.setVisible(false);
                    } else {

                        jLabel6.setText("Nº PCs debe coincidir con filas de A!");

                    }

                } else {
                    jLabel6.setText("filas de A deben coincidir con columnas de B!");

                }
                break;

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
